### ISSUE TITLE
change colors?

### ISSUE THREAD

**Issue by markiaaan** [qurator-spk/neath#33]
change the yellow (for highlighting) to something less saturated/more pleasing to the eyes? consider design for color vision deficiency (even though I think it is not that important, since there are labels anyway)? ( https://projects.susielu.com/viz-palette )

color palette generator: https://medialab.github.io/iwanthue

**Comment by cneud** [comment]
Thanks, we've already been considering a different palette but so far we're lacking an understanding of what's _good_. The suggested links definitely help.

**Comment by cneud** [comment]
@snmnzl @markiaaan I've now changed the color palette to sth that is supposedly more distinct and  suitable for color-blind. Plz check the according [branch](https://github.com/qurator-spk/neath/tree/patch-palette-1) and let me know what you think.

**Comment by snmnzl** [comment]
@cneud, thank you! We've read Wong 2011 and checked out the new palette. We are generally very happy with the better accessibility in case of colour blindness, but have some suggestions for slight changes (see file attached).
This especially concerns: #df6caa instead of "plum" and #a60a2d as 7th colour instead of "olive"
![grafik](https://user-images.githubusercontent.com/56627609/72057517-d36cdc00-32ce-11ea-99fd-81d659abd3e6.png)

**Comment by cneud** [comment]
fixed in a791de682aacd3a07c2ead2cf1c3bf8faee64048
